create or replace PROCEDURE DODAJ_PRODUKT 
(
  V_ILOSC IN NUMBER 
, V_CENA IN NUMBER 
, V_NAZWA IN VARCHAR2
, V_MARKA IN VARCHAR2
) AS 
BEGIN
  INSERT INTO PRODUKT
  (ILOSC,CENA)
  values (V_ILOSC,V_CENA);
  INSERT INTO PRODUKT_SLOWNIK
  values(SEQ_PRODUKT.CURRVAL,V_NAZWA,V_MARKA);
  COMMIT;
END DODAJ_PRODUKT;
