create or replace PROCEDURE USUN_FAKTURE 
(
  V_NR_FAKTURY IN NUMBER 
) AS 
BEGIN
  DELETE POZYCJA_FAKTURY
  WHERE NR_FAKTURY=V_NR_FAKTURY;
  DELETE NAGLOWEK_FAKTURY
  WHERE NR_FAKTURY=V_NR_FAKTURY;
  
END USUN_FAKTURE;
