create or replace TRIGGER TR_POZYCJA_DL 
BEFORE DELETE ON POZYCJA_FAKTURY
FOR EACH ROW
DECLARE
V_ILOSC number;
V_KOD number;
V_WARTOSC number;
V_NR number;

BEGIN
  V_ILOSC:=:OLD.ILOSC;
  V_KOD:=:OLD.KOD_PRODUKTU;
  V_NR:=:OLD.NR_FAKTURY;

  UPDATE PRODUKT
  SET ILOSC=ILOSC+V_ILOSC
  WHERE KOD_PRODUKTU=V_KOD;
  
  SELECT CENA into V_WARTOSC from PRODUKT
  where KOD_PRODUKTU=V_KOD;
  
  V_WARTOSC:=V_WARTOSC*V_ILOSC;
  UPDATE NAGLOWEK_FAKTURY
  SET WARTOSC=WARTOSC-V_WARTOSC
  WHERE NR_FAKTURY=V_NR;
  
  
END;
