-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2019-02-28 11:37:05 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE SEQUENCE seq_faktura START WITH 10000 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 10000;

CREATE SEQUENCE seq_klient START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1;

CREATE SEQUENCE seq_produkt START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1;

CREATE TABLE klient (
    nr_klienta           NUMBER(10) NOT NULL,
    kod_pocztowy         VARCHAR2(6) NOT NULL,
    kod_ulicy            VARCHAR2(5) NOT NULL,
    imie                 VARCHAR2(30) NOT NULL,
    nazwisko             VARCHAR2(30) NOT NULL,
    numer_zameldowania   NUMBER(10) NOT NULL,
    telefon              NUMBER(11),
    mail                 VARCHAR2(40)
)
    LOGGING;

ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( nr_klienta );

CREATE TABLE miasto (
    kod_pocztowy   VARCHAR2(6) NOT NULL,
    miasto         VARCHAR2(30) NOT NULL
)
    LOGGING;

ALTER TABLE miasto ADD CONSTRAINT miasto_pk PRIMARY KEY ( kod_pocztowy );

CREATE TABLE naglowek_faktury (
    nr_faktury     NUMBER(10) NOT NULL,
    nr_klienta     NUMBER(10) NOT NULL,
    data_faktury   DATE NOT NULL,
    wartosc        NUMBER(20,2) NOT NULL
)
    LOGGING;

ALTER TABLE naglowek_faktury ADD CONSTRAINT naglowek_faktury_pk PRIMARY KEY ( nr_faktury );

CREATE TABLE pozycja_faktury (
    nr_faktury     NUMBER(10) NOT NULL,
    kod_produktu   NUMBER(10) NOT NULL,
    ilosc          NUMBER(5) NOT NULL,
    naleznosc      NUMBER(20,2) NOT NULL
)
    LOGGING;

ALTER TABLE pozycja_faktury ADD CONSTRAINT pozycja_faktury_pk PRIMARY KEY ( nr_faktury,kod_produktu );

CREATE TABLE produkt (
    kod_produktu   NUMBER(10) NOT NULL,
    ilosc          NUMBER(6) NOT NULL,
    cena           NUMBER(20,2) NOT NULL
)
    LOGGING;

ALTER TABLE produkt ADD CONSTRAINT produkt_pk PRIMARY KEY ( kod_produktu );

CREATE TABLE produkt_slownik (
    kod_produktu   NUMBER(10) NOT NULL,
    nazwa          VARCHAR2(30) NOT NULL,
    marka          VARCHAR2(30) NOT NULL
)
    LOGGING;

ALTER TABLE produkt_slownik ADD CONSTRAINT produkt_slownik_pk PRIMARY KEY ( kod_produktu );

CREATE TABLE ulica (
    kod_ulicy   VARCHAR2(5) NOT NULL,
    ulica       VARCHAR2(30) NOT NULL
)
    LOGGING;

ALTER TABLE ulica ADD CONSTRAINT ulica_pk PRIMARY KEY ( kod_ulicy );

ALTER TABLE klient
    ADD CONSTRAINT klient_miasto_fk FOREIGN KEY ( kod_pocztowy )
        REFERENCES miasto ( kod_pocztowy )
    NOT DEFERRABLE;

ALTER TABLE klient
    ADD CONSTRAINT klient_ulica_fk FOREIGN KEY ( kod_ulicy )
        REFERENCES ulica ( kod_ulicy )
    NOT DEFERRABLE;

ALTER TABLE naglowek_faktury
    ADD CONSTRAINT naglowek_faktury_klient_fk FOREIGN KEY ( nr_klienta )
        REFERENCES klient ( nr_klienta )
    NOT DEFERRABLE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE pozycja_faktury
    ADD CONSTRAINT pozycja_faktury_naglowek_faktury_fk FOREIGN KEY ( nr_faktury )
        REFERENCES naglowek_faktury ( nr_faktury )
    NOT DEFERRABLE;

ALTER TABLE pozycja_faktury
    ADD CONSTRAINT pozycja_faktury_produkt_fk FOREIGN KEY ( kod_produktu )
        REFERENCES produkt ( kod_produktu )
    NOT DEFERRABLE;

ALTER TABLE produkt_slownik
    ADD CONSTRAINT produkt_slownik_produkt_fk FOREIGN KEY ( kod_produktu )
        REFERENCES produkt ( kod_produktu )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
